

spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:postgresql://localhost:5432/driverdb
    username: postgres
    password: joel.2427
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
redis:
  host: localhost
  port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/